spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/gulimall_ums
  application:
    name: gulimall-member
  cloud:
    nacos:
#      config:
#        server-addr: 127.0.0.1:8848
      discovery:
        ip: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 自增主键

server:
  port: 8000